# Gitleaks configuration for EPay
# https://github.com/gitleaks/gitleaks#configuration

title = "EPay Gitleaks Config"

[allowlist]
  description = "Global allowlist"
  paths = [
    "pnpm-lock.yaml",
    "node_modules/",
    "dist/",
    ".turbo/",
    "coverage/",
    ".next/",
  ]

[extend]
  useDefault = true
