{{- if .Values.podDisruptionBudget.enabled }}
{{- if .Values.api.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "epay.fullname" . }}-api
  labels:
    {{- include "epay.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "epay.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
---
{{- end }}
{{- range .Values.frontends }}
{{- if .enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "epay.fullname" $ }}-{{ .name }}
  labels:
    {{- include "epay.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "epay.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ .name }}
---
{{- end }}
{{- end }}
{{- end }}
